### ISSUE TITLE
Support touchscreen intel 11th gen (SP7+)

### ISSUE THREAD

**Issue by ghost** [linux-surface/intel-precise-touch#10]
Hi!,

I see this video on youtube:
https://www.youtube.com/watch?v=RAoJIdMJInw

The guy in that vide install ubuntu 21.04 on a Lenovo IdeaPad Flex  with 11th Gen Intel Core i5-1135G7 processor and the touchscreen works "out of the box" (min 3.05)

This is exactly the same processor of my SP7+.

In my first post in this linux-surface hub i understand that the problem was related with the 11th intel touch driver, but in this video works fine.

The are something i can try to make it work?

I tryied too 21.04 with the latest mainline kernel 5.12.7 and the latest availible on surface-linux (5.12.6), and dont work in booth latest kernels.

Regards.

**Comment by qzed** [comment]
This is already tracked in https://github.com/linux-surface/intel-precise-touch/issues/8. The problem is that Intel switched their IPTS interface from MEI to PCIe. Unfortunately no one of us devs have a device with that new interface and there doesn't seem to be any specification/documentation/code-dump by Intel available right now.

The reason this works on the Lenovo device is that it doesn't use IPTS for touch input (pretty much no device outside of the Surface line uses that). It instead uses either some generic USB-HID or some I2C or SPI device with a driver that's already in the kernel.
